### ISSUE TITLE
IE Auto Login

### ISSUE THREAD

**Issue by joe-singer** [missinglink/passport-facebook-canvas#4]
I am using the Auto Login route as suggested in the readme and everything functions normally in all browsers except IE (All versions). I am using angular-fullstack generator. I get "UnauthorizedError: No Authorization header was found" any suggestions?

**Comment by joe-singer** [comment]
It was an issue with p3p. I used https://github.com/troygoode/node-p3p
```
.post("/canvas", p3p(p3p.recommended), passport.authenticate("facebook-canvas", {
```

**Comment by missinglink** [comment]
Do you think it's worth adding this as a default?
