### ISSUE TITLE
Will this work with latest version of passport-facebook?

### ISSUE THREAD

**Issue by skrichten** [missinglink/passport-facebook-canvas#7]
This project hasn't been updated in a long time.  Anyone know if it still works with the latest version of passport-facebook?  Any tips on supporting both strategies in one app would be helpful as well.  I'm using generator-angular-fullstack as a starting point.
https://github.com/angular-fullstack/generator-angular-fullstack

**Comment by missinglink** [comment]
I haven't used it in a while, there were some fixes contributed about 9 months ago to keep up-to-date with facebook policies, it was working fine then.

In the past people have opened issues when there were problems.
Is there a particular change in passport-facebook that you think might cause a problem?

**Comment by skrichten** [comment]
Sorry, I see now you have 1.0 as your own dependency.  Passport-facebook is now at 2.0 and angular fullstack is using that.  I'll just have to see if I can integrate passport-facebook-canvas into generator-angular-fullstack.

**Comment by missinglink** [comment]
hi @skrichten I'm still a little confused, this is a server-side only package for nodejs. how does it relate to angular-fullstack? isn't angular a front-end only framework?

**Comment by skrichten** [comment]
generator-angular-fullstack is a yeoman generator that serves as a nice starting point for a MEAN stack project...

https://github.com/angular-fullstack/generator-angular-fullstack

**Comment by missinglink** [comment]
I see... if you're going to writing a facebook canvas app it should be pretty easy to modify, just follow the readme on this repo.

If that solves your problem could you please close your issue?
